version: 0.0
os: linux

files:
  - source: files/index.html
    destination: /var/www/html

permissions:
  - object: /var/www/html
    pattern: index.html
    mode: 755
    type:
      - file

hooks:
  BeforeInstall:
    - location: scripts/httpd-stop.sh
  AfterInstall:
    - location: scripts/httpd-start.sh