version: 0.0
os: linux

files:
  - source: files/app
    destination: /var/www/html

permissions:
  - object: /var/www/html
    pattern: files/app
    mode: 755
    type:
      - directory

hooks:
  BeforeInstall:
    - location: scripts/httpd-stop.sh
  AfterInstall:
    - location: scripts/httpd-start.sh